#Configurations for material Shadow.
[general]
	#The module blacklist of this material. "*" is an alias for all modules. If a module name occurs an odd number of times (including wildcards), then the module is blacklisted.
	moduleBlacklist = []
	#The alternative names of this material.
	alternativeNames = []
	#The color of this material.
	color = 1644325
	#The byproducts of this material.
	extras = []
	#The model type of the material.
	modelType = "metallic"
	#Should items of this material have the enchanted glow.
	hasEffect = false
	#Is the storage block of this material small (2x2).
	isSmallStorageBlock = false
[molten]
	#The temperature of this molten fluid.
	temperature = 1300
[enderio]
	#The default byproduct material to output in Ender IO's sagmill.
	byproduct = "minecraft:cobblestone"
[tconstruct]
	#The base smeltery temperature of this material.
	temperature = 600
